<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    public function run()
    {
        $rows = [
            ['ci_birth_cd' => 'أذربيجان', 'flag' => 'azerbaijan.svg', 'code' => 'AZ'],
            ['ci_birth_cd' => 'آسيا غير معروف', 'flag' => '', 'code' => 'AS'],
            ['ci_birth_cd' => 'أفغانستان', 'flag' => 'afghanistan.svg', 'code' => 'AF'],
            ['ci_birth_cd' => 'ألبانيا', 'flag' => 'albania.svg', 'code' => 'AL'],
            ['ci_birth_cd' => 'ألمانيا', 'flag' => 'germany.svg', 'code' => 'DE'],
            ['ci_birth_cd' => 'إيران', 'flag' => 'iran.svg', 'code' => 'IR'],
            ['ci_birth_cd' => 'إيرلندا', 'flag' => 'ireland.svg', 'code' => 'IE'],
            ['ci_birth_cd' => 'آيسلندا', 'flag' => 'iceland.svg', 'code' => 'IS'],
            ['ci_birth_cd' => 'إيطاليا', 'flag' => 'italy.svg', 'code' => 'IT'],
            ['ci_birth_cd' => 'اثيوبيا', 'flag' => 'ethiopia.svg', 'code' => 'ET'],
            ['ci_birth_cd' => 'ارتيريا', 'flag' => 'eritrea.svg', 'code' => 'ER'],
            ['ci_birth_cd' => 'اسبانيا', 'flag' => 'spain.svg', 'code' => 'ES'],
            ['ci_birth_cd' => 'استراليا', 'flag' => 'australia.svg', 'code' => 'AU'],
            ['ci_birth_cd' => 'استونيا', 'flag' => 'estonia.svg', 'code' => 'EE'],
            ['ci_birth_cd' => 'اسرائيل', 'flag' => 'israel.svg', 'code' => 'IL'],
            ['ci_birth_cd' => 'اسكتلندا', 'flag' => 'scotland.svg', 'code' => 'GB-SCT'],
            ['ci_birth_cd' => 'اكوادور', 'flag' => 'ecuador.svg', 'code' => 'EC'],
            ['ci_birth_cd' => 'الأرجنتين', 'flag' => 'argentina.svg', 'code' => 'AR'],
            ['ci_birth_cd' => 'الاتحاد السوفيتي', 'flag' => '', 'code' => 'SU'],
            ['ci_birth_cd' => 'الاردن', 'flag' => 'jordan.svg', 'code' => 'JO'],
            ['ci_birth_cd' => 'الامارات', 'flag' => 'united-arab-emirates.svg', 'code' => 'AE'],
            ['ci_birth_cd' => 'البحرين', 'flag' => 'bahrain.svg', 'code' => 'BH'],
            ['ci_birth_cd' => 'البرازيل', 'flag' => 'brazil.svg', 'code' => 'BR'],
            ['ci_birth_cd' => 'البرتغال', 'flag' => 'portugal.svg', 'code' => 'PT'],
            ['ci_birth_cd' => 'البوسنة', 'flag' => 'bosnia-and-herzegovina.svg', 'code' => 'BA'],
            ['ci_birth_cd' => 'الجزائر', 'flag' => 'algeria.svg', 'code' => 'DZ'],
            ['ci_birth_cd' => 'الدنمارك', 'flag' => 'denmark.svg', 'code' => 'DK'],
            ['ci_birth_cd' => 'السعودية', 'flag' => 'saudi-arabia.svg', 'code' => 'SA'],
            ['ci_birth_cd' => 'السنغال', 'flag' => 'senegal.svg', 'code' => 'SN'],
            ['ci_birth_cd' => 'السودان', 'flag' => 'sudan.svg', 'code' => 'SD'],
            ['ci_birth_cd' => 'السويد', 'flag' => 'sweden.svg', 'code' => 'SE'],
            ['ci_birth_cd' => 'الصومال', 'flag' => 'somalia.svg', 'code' => 'SO'],
            ['ci_birth_cd' => 'الصين', 'flag' => 'china.svg', 'code' => 'CN'],
            ['ci_birth_cd' => 'الضفة الغربية', 'flag' => 'palestine.svg', 'code' => 'PS-WB'],
            ['ci_birth_cd' => 'العراق', 'flag' => 'iraq.svg', 'code' => 'IQ'],
            ['ci_birth_cd' => 'الفلبين', 'flag' => 'philippines.svg', 'code' => 'PH'],
            ['ci_birth_cd' => 'الكويت', 'flag' => 'kuwait.svg', 'code' => 'KW'],
            ['ci_birth_cd' => 'المانيا الشرقية', 'flag' => '', 'code' => 'DDR'],
            ['ci_birth_cd' => 'المجر', 'flag' => 'hungary.svg', 'code' => 'HU'],
            ['ci_birth_cd' => 'المغرب', 'flag' => 'morocco.svg', 'code' => 'MA'],
            ['ci_birth_cd' => 'المكسيك', 'flag' => 'mexico.svg', 'code' => 'MX'],
            ['ci_birth_cd' => 'المملكة المتحدة', 'flag' => 'united-kingdom.svg', 'code' => 'GB'],
            ['ci_birth_cd' => 'النرويج', 'flag' => 'norway.svg', 'code' => 'NO'],
            ['ci_birth_cd' => 'النمسا', 'flag' => 'austria.svg', 'code' => 'AT'],
            ['ci_birth_cd' => 'النيجر', 'flag' => 'niger.svg', 'code' => 'NE'],
            ['ci_birth_cd' => 'الهند', 'flag' => 'india.svg', 'code' => 'IN'],
            ['ci_birth_cd' => 'الولايات المتحدة', 'flag' => 'united-states.svg', 'code' => 'US'],
            ['ci_birth_cd' => 'اليابان', 'flag' => 'japan.svg', 'code' => 'JP'],
            ['ci_birth_cd' => 'اليمن', 'flag' => 'yemen.svg', 'code' => 'YE'],
            ['ci_birth_cd' => 'اليمن الشعبية', 'flag' => 'yemen.svg', 'code' => 'YE-PDR'],
            ['ci_birth_cd' => 'اليونان', 'flag' => 'greece.svg', 'code' => 'GR'],
            ['ci_birth_cd' => 'اندونيسيا', 'flag' => 'indonesia.svg', 'code' => 'ID'],
            ['ci_birth_cd' => 'اوزباكستان', 'flag' => 'uzbekistan.svg', 'code' => 'UZ'],
            ['ci_birth_cd' => 'اوغندا', 'flag' => 'uganda.svg', 'code' => 'UG'],
            ['ci_birth_cd' => 'اوكرانيا', 'flag' => 'ukraine.svg', 'code' => 'UA'],
            ['ci_birth_cd' => 'باكستان', 'flag' => 'pakistan.svg', 'code' => 'PK'],
            ['ci_birth_cd' => 'بلجيكا', 'flag' => 'belgium.svg', 'code' => 'BE'],
            ['ci_birth_cd' => 'بلغاريا', 'flag' => 'bulgaria.svg', 'code' => 'BG'],
            ['ci_birth_cd' => 'بنغلادش', 'flag' => 'bangladesh.svg', 'code' => 'BD'],
            ['ci_birth_cd' => 'بولندا', 'flag' => 'poland.svg', 'code' => 'PL'],
            ['ci_birth_cd' => 'بوليفيا', 'flag' => 'bolivia.svg', 'code' => 'BO'],
            ['ci_birth_cd' => 'بيرو', 'flag' => 'peru.svg', 'code' => 'PE'],
            ['ci_birth_cd' => 'تايلاند', 'flag' => 'thailand.svg', 'code' => 'TH'],
            ['ci_birth_cd' => 'تركمانستان', 'flag' => 'turkmenistan.svg', 'code' => 'TM'],
            ['ci_birth_cd' => 'تركيا', 'flag' => 'turkey.svg', 'code' => 'TR'],
            ['ci_birth_cd' => 'تشيك', 'flag' => '', 'code' => 'CZ'],
            ['ci_birth_cd' => 'تشيكوسلوفاكيا', 'flag' => '', 'code' => 'CS'],
            ['ci_birth_cd' => 'تشيلي', 'flag' => 'chile.svg', 'code' => 'CL'],
            ['ci_birth_cd' => 'تنزانيا', 'flag' => 'tanzania.svg', 'code' => 'TZ'],
            ['ci_birth_cd' => 'توجو', 'flag' => '', 'code' => 'TG'],
            ['ci_birth_cd' => 'تونس', 'flag' => 'tunisia.svg', 'code' => 'TN'],
            ['ci_birth_cd' => 'جنوب إفريقيا', 'flag' => 'south-africa.svg', 'code' => 'ZA'],
            ['ci_birth_cd' => 'جورجيا', 'flag' => 'georgia.svg', 'code' => 'GE'],
            ['ci_birth_cd' => 'جيبوتي', 'flag' => 'djibouti.svg', 'code' => 'DJ'],
            ['ci_birth_cd' => 'داهومي', 'flag' => '', 'code' => 'BJ'],
            ['ci_birth_cd' => 'روسيا', 'flag' => 'russia.svg', 'code' => 'RU'],
            ['ci_birth_cd' => 'روسيا البيضاء', 'flag' => 'belarus.svg', 'code' => 'BY'],
            ['ci_birth_cd' => 'رومانيا', 'flag' => 'romania.svg', 'code' => 'RO'],
            ['ci_birth_cd' => 'زيمبابوي', 'flag' => 'zimbabwe.svg', 'code' => 'ZW'],
            ['ci_birth_cd' => 'ساحل العاج', 'flag' => 'ivory-coast.svg', 'code' => 'CI'],
            ['ci_birth_cd' => 'سراييفو', 'flag' => '', 'code' => 'BA'],
            ['ci_birth_cd' => 'سريلانكا', 'flag' => 'sri-lanka.svg', 'code' => 'LK'],
            ['ci_birth_cd' => 'سلطنة عمان', 'flag' => 'oman.svg', 'code' => 'OM'],
            ['ci_birth_cd' => 'سلوفاكيا', 'flag' => 'slovakia.svg', 'code' => 'SK'],
            ['ci_birth_cd' => 'سلوفينيا', 'flag' => 'slovenia.svg', 'code' => 'SI'],
            ['ci_birth_cd' => 'سوريا', 'flag' => 'syria.svg', 'code' => 'SY'],
            ['ci_birth_cd' => 'سويسرا', 'flag' => 'switzerland.svg', 'code' => 'CH'],
            ['ci_birth_cd' => 'صربيا', 'flag' => 'serbia.svg', 'code' => 'RS'],
            ['ci_birth_cd' => 'طاجكستان', 'flag' => 'tajikistan.svg', 'code' => 'TJ'],
            ['ci_birth_cd' => 'عدن', 'flag' => '', 'code' => 'ADN'],
            ['ci_birth_cd' => 'غانا', 'flag' => 'ghana.svg', 'code' => 'GH'],
            ['ci_birth_cd' => 'غمبيا', 'flag' => 'gambia.svg', 'code' => 'GM'],
            ['ci_birth_cd' => 'غير مسجل', 'flag' => '', 'code' => 'UNR'],
            ['ci_birth_cd' => 'غير مسجل-ملغى', 'flag' => '', 'code' => 'CNL'],
            ['ci_birth_cd' => 'غينيا', 'flag' => 'guinea.svg', 'code' => 'GN'],
            ['ci_birth_cd' => 'فرنسا', 'flag' => 'france.svg', 'code' => 'FR'],
            ['ci_birth_cd' => 'فلسطين الداخل(48)', 'flag' => 'palestine.svg', 'code' => 'PS-48'],
            ['ci_birth_cd' => 'فنلندا', 'flag' => 'finland.svg', 'code' => 'FI'],
            ['ci_birth_cd' => 'فيتنام', 'flag' => 'vietnam.svg', 'code' => 'VN'],
            ['ci_birth_cd' => 'قبرص', 'flag' => 'cyprus.svg', 'code' => 'CY'],
            ['ci_birth_cd' => 'قطاع غزة', 'flag' => 'palestine.svg', 'code' => 'PS-G'],
            ['ci_birth_cd' => 'قطاع غزة وشمالي سيناء', 'flag' => '', 'code' => 'PS-GS'],
            ['ci_birth_cd' => 'قطر', 'flag' => 'qatar.svg', 'code' => 'QA'],
            ['ci_birth_cd' => 'قيرغيزستان', 'flag' => 'kyrgyzstan.svg', 'code' => 'KG'],
            ['ci_birth_cd' => 'كازاخستان', 'flag' => 'kazakhstan.svg', 'code' => 'KZ'],
            ['ci_birth_cd' => 'كرواتيا', 'flag' => 'croatia.svg', 'code' => 'HR'],
            ['ci_birth_cd' => 'كندا', 'flag' => 'canada.svg', 'code' => 'CA'],
            ['ci_birth_cd' => 'كوبا', 'flag' => 'cuba.svg', 'code' => 'CU'],
            ['ci_birth_cd' => 'كوريا', 'flag' => 'south-korea.svg', 'code' => 'KR'],
            ['ci_birth_cd' => 'كوستاريكا', 'flag' => 'costa-rica.svg', 'code' => 'CR'],
            ['ci_birth_cd' => 'كوسوفو', 'flag' => 'kosovo.svg', 'code' => 'XK'],
            ['ci_birth_cd' => 'كولومبيا', 'flag' => 'colombia.svg', 'code' => 'CO'],
            ['ci_birth_cd' => 'كيرغزستان', 'flag' => 'kyrgyzstan.svg', 'code' => 'KG'],
            ['ci_birth_cd' => 'لاوس', 'flag' => 'laos.svg', 'code' => 'LA'],
            ['ci_birth_cd' => 'لبنان', 'flag' => 'lebanon.svg', 'code' => 'LB'],
            ['ci_birth_cd' => 'لتوانيا', 'flag' => 'lithuania.svg', 'code' => 'LT'],
            ['ci_birth_cd' => 'ليبيا', 'flag' => 'libya.svg', 'code' => 'LY'],
            ['ci_birth_cd' => 'ليبيريا', 'flag' => 'liberia.svg', 'code' => 'LR'],
            ['ci_birth_cd' => 'مارتينيك', 'flag' => 'martinique.svg', 'code' => 'MQ'],
            ['ci_birth_cd' => 'مالديفيا', 'flag' => 'maldives.svg', 'code' => 'MV'],
            ['ci_birth_cd' => 'مالطا', 'flag' => 'malta.svg', 'code' => 'MT'],
            ['ci_birth_cd' => 'مالي', 'flag' => 'mali.svg', 'code' => 'ML'],
            ['ci_birth_cd' => 'ماليزيا', 'flag' => 'malaysia.svg', 'code' => 'MY'],
            ['ci_birth_cd' => 'مصر', 'flag' => 'egypt.svg', 'code' => 'EG'],
            ['ci_birth_cd' => 'مقدونيا', 'flag' => 'republic-of-macedonia.svg', 'code' => 'MK'],
            ['ci_birth_cd' => 'مكاو', 'flag' => '', 'code' => 'MO'],
            ['ci_birth_cd' => 'منجوليا', 'flag' => 'mongolia.svg', 'code' => 'MN'],
            ['ci_birth_cd' => 'موريتانيا', 'flag' => 'mauritania.svg', 'code' => 'MR'],
            ['ci_birth_cd' => 'مولدافيه', 'flag' => 'moldova.svg', 'code' => 'MD'],
            ['ci_birth_cd' => 'نيجيريا', 'flag' => 'nigeria.svg', 'code' => 'NG'],
            ['ci_birth_cd' => 'نيكاراغوا', 'flag' => 'nicaragua.svg', 'code' => 'NI'],
            ['ci_birth_cd' => 'نيو زيلاندا', 'flag' => 'new-zealand.svg', 'code' => 'NZ'],
            ['ci_birth_cd' => 'هولندا', 'flag' => 'netherlands.svg', 'code' => 'NL'],
            ['ci_birth_cd' => 'يوغوسلافيا', 'flag' => '', 'code' => 'YU'],
        ];

        $existingCodes = DB::table('ci_birth_cd')->pluck('code')->flip();
        $existingNames = DB::table('ci_birth_cd')->pluck('ci_birth_cd')->flip();

        $rows = array_values(array_filter($rows, function (array $row) use ($existingCodes, $existingNames) {
            // كود موجود => تحديثه، اسم غير موجود => إدخاله،
            // اسم موجود بكود آخر => تخطيه (كود بديل لدولة موجودة)
            return isset($existingCodes[$row['code']]) || !isset($existingNames[$row['ci_birth_cd']]);
        }));

        if ($rows !== []) {
            DB::table('ci_birth_cd')->upsert($rows, ['code'], ['ci_birth_cd', 'flag']);
        }
    }
}
