<?php

return [
    /*
    |--------------------------------------------------------------------------
    | خريطة حقول الجمعيات
    |--------------------------------------------------------------------------
    |
    | هذا الملف يحتوي على mapping بين أسماء الحقول في الجدول وأسمائها المعروضة
    |
    */

    'fields' => [
        // معلومات المكفول الأساسية
        'field_sponsor_name' => [
            'id' => 1,
            'db_column' => 'field_sponsor_name',
            'display_name' => 'إسم المكفول',
            'category' => 'معلومات المكفول الأساسية',
            'category_id' => 1,
            'order' => 1,
            'required' => true,
        ],
        'field_identity_number' => [
            'id' => 2,
            'db_column' => 'field_identity_number',
            'display_name' => 'رقم الهوية',
            'category' => 'معلومات المكفول الأساسية',
            'category_id' => 1,
            'order' => 2,
            'required' => false,
        ],
        'field_person_birth_date' => [
            'id' => 3,
            'db_column' => 'field_person_birth_date',
            'display_name' => 'تاريخ الميلاد',
            'category' => 'معلومات المكفول الأساسية',
            'category_id' => 1,
            'order' => 3,
            'required' => false,
        ],

        // معلومات السكن
        'field_housing_status' => [
            'id' => 5,
            'db_column' => 'field_housing_status',
            'display_name' => 'حالة السكن',
            'category' => 'معلومات السكن',
            'category_id' => 2,
            'order' => 5,
            'required' => false,
        ],
        'field_housing_type' => [
            'id' => 6,
            'db_column' => 'field_housing_type',
            'display_name' => 'نوع السكن',
            'category' => 'معلومات السكن',
            'category_id' => 2,
            'order' => 6,
            'required' => false,
        ],
        'field_housing_address_detail' => [
            'id' => 8,
            'db_column' => 'field_housing_address_detail',
            'display_name' => 'عنوان السكن التفصيلي',
            'category' => 'معلومات السكن',
            'category_id' => 2,
            'order' => 8,
            'required' => false,
        ],
        'field_house_demolition' => [
            'id' => 9,
            'db_column' => 'field_house_demolition',
            'display_name' => 'هل المنزل هدم كلي او جزئي',
            'category' => 'معلومات السكن',
            'category_id' => 2,
            'order' => 9,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['غير مهدوم', 'هدم جزئي', 'هدم كلي'],
        ],
        'field_house_repair_need' => [
            'id' => 10,
            'db_column' => 'field_house_repair_need',
            'display_name' => 'هل المنزل بحاجة الى ترميم او بناء',
            'category' => 'معلومات السكن',
            'category_id' => 2,
            'order' => 10,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['لا يحتاج', 'ترميم', 'بناء جزئي', 'بناء كامل'],
        ],

        // المعلومات الدراسية
        'field_school_name' => [
            'id' => 11,
            'db_column' => 'field_school_name',
            'display_name' => 'اسم المدرسة',
            'category' => 'المعلومات الدراسية',
            'category_id' => 3,
            'order' => 11,
            'required' => false,
        ],
        'field_school_address' => [
            'id' => 12,
            'db_column' => 'field_school_address',
            'display_name' => 'عنوان المدرسة',
            'category' => 'المعلومات الدراسية',
            'category_id' => 3,
            'order' => 12,
            'required' => false,
        ],
        'field_grade' => [
            'id' => 13,
            'db_column' => 'field_grade',
            'display_name' => 'الصف',
            'category' => 'المعلومات الدراسية',
            'category_id' => 3,
            'order' => 13,
            'required' => false,
            'type' => 'dropdown',
            'source' => 'academic_degrees',
        ],
        'field_student_level' => [
            'id' => 16,
            'db_column' => 'field_student_level',
            'display_name' => 'مستوى الطالب',
            'category' => 'المعلومات الدراسية',
            'category_id' => 3,
            'order' => 14,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['ممتاز', 'جيد جدًا', 'جيد', 'متوسط', 'ضعيف'],
        ],
        'field_weakness_reason' => [
            'id' => 17,
            'db_column' => 'field_weakness_reason',
            'display_name' => 'سبب الضعف',
            'category' => 'المعلومات الدراسية',
            'category_id' => 3,
            'order' => 15,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['ظروف نفسية', 'ظروف مادية', 'انقطاع عن الدراسة', 'صعوبات تعلم', 'مرض', 'لا يوجد'],
        ],
        'field_tent_school' => [
            'id' => 18,
            'db_column' => 'field_tent_school',
            'display_name' => 'هل يكمل تعليمه في خيمة مدرسية',
            'category' => 'المعلومات الدراسية',
            'category_id' => 3,
            'order' => 16,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['نعم', 'لا'],
        ],
        'field_orphan_ambition' => [
            'id' => 19,
            'db_column' => 'field_orphan_ambition',
            'display_name' => 'طموح اليتيم',
            'category' => 'المعلومات الدراسية',
            'category_id' => 3,
            'order' => 19,
            'required' => false,
        ],

        // الحالة النفسية والسلوكية
        'field_psychological_state' => [
            'id' => 20,
            'db_column' => 'field_psychological_state',
            'display_name' => 'الحالة النفسية',
            'category' => 'الحالة النفسية والسلوكية',
            'category_id' => 4,
            'order' => 20,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['مستقرة', 'قلق', 'اكتئاب', 'صدمة نفسية', 'بحاجة متابعة'],
        ],
        'field_behavioral_state' => [
            'id' => 21,
            'db_column' => 'field_behavioral_state',
            'display_name' => 'الحالة السلوكية',
            'category' => 'الحالة النفسية والسلوكية',
            'category_id' => 4,
            'order' => 21,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['جيدة', 'عدوانية', 'انطوائية', 'فرط حركة', 'طبيعية'],
        ],
        'field_orphan_behavior' => [
            'id' => 22,
            'db_column' => 'field_orphan_behavior',
            'display_name' => 'سلوك اليتيم',
            'category' => 'الحالة النفسية والسلوكية',
            'category_id' => 4,
            'order' => 22,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['ملتزم', 'متوسط', 'غير منضبط'],
        ],

        // الجوانب الدينية
        'field_religious_commitment' => [
            'id' => 23,
            'db_column' => 'field_religious_commitment',
            'display_name' => 'الإلتزام الديني',
            'category' => 'الجوانب الدينية',
            'category_id' => 5,
            'order' => 23,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['ملتزم', 'متوسط', 'ضعيف'],
        ],
        'field_commitment' => [
            'id' => 24,
            'db_column' => 'field_commitment',
            'display_name' => 'التزامه',
            'category' => 'الجوانب الدينية',
            'category_id' => 5,
            'order' => 24,
            'required' => false,
        ],
        'field_quran_memorization' => [
            'id' => 25,
            'db_column' => 'field_quran_memorization',
            'display_name' => 'مقدار حفظه للقرآن',
            'category' => 'الجوانب الدينية',
            'category_id' => 5,
            'order' => 25,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['لا يحفظ', 'جزء', '2–5 أجزاء', 'أكثر من 5 أجزاء'],
        ],
        'field_prayer_commitment' => [
            'id' => 26,
            'db_column' => 'field_prayer_commitment',
            'display_name' => 'التزام اليتيم بالصلاة',
            'category' => 'الجوانب الدينية',
            'category_id' => 5,
            'order' => 26,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['دائمًا', 'أحيانًا', 'نادرًا'],
        ],

        // الحالة الصحية
        'field_health_status' => [
            'id' => 27,
            'db_column' => 'field_health_status',
            'display_name' => 'الحالة الصحية للمكفول',
            'category' => 'الحالة الصحية',
            'category_id' => 6,
            'order' => 27,
            'required' => false,
        ],
        'field_receives_treatment' => [
            'id' => 31,
            'db_column' => 'field_receives_treatment',
            'display_name' => 'هل يتلقى العلاج',
            'category' => 'الحالة الصحية',
            'category_id' => 6,
            'order' => 28,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['لا', 'نعم'],
        ],
        'field_orphan_health' => [
            'id' => 28,
            'db_column' => 'field_orphan_health',
            'display_name' => 'الوضع الصحي للمكفول',
            'category' => 'الحالة الصحية',
            'category_id' => 6,
            'order' => 29,
            'required' => false,
            'depends_on' => 'field_receives_treatment',
            'show_when' => 'نعم',
        ],
        'field_treatment_cost' => [
            'id' => 30,
            'db_column' => 'field_treatment_cost',
            'display_name' => 'تكاليف العلاج',
            'category' => 'الحالة الصحية',
            'category_id' => 6,
            'order' => 30,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['لا يوجد', 'بسيطة', 'متوسطة', 'مرتفعة'],
            'depends_on' => 'field_receives_treatment',
            'show_when' => 'نعم',
        ],
        'field_family_sick_member' => [
            'id' => 32,
            'db_column' => 'field_family_sick_member',
            'display_name' => 'هل يوجد أحد من افراد الأسرة مريض',
            'category' => 'الحالة الصحية',
            'category_id' => 6,
            'order' => 32,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['لا', 'نعم'],
        ],
        'field_family_disease_cost' => [
            'id' => 33,
            'db_column' => 'field_family_disease_cost',
            'display_name' => 'نوع المرض او الإصابة مع التكاليف',
            'category' => 'الحالة الصحية',
            'category_id' => 6,
            'order' => 33,
            'required' => false,
        ],

        // احتياجات وإبداع
        'field_orphan_needs' => [
            'id' => 34,
            'db_column' => 'field_orphan_needs',
            'display_name' => 'احتياجات المكفول',
            'category' => 'احتياجات وإبداع',
            'category_id' => 7,
            'order' => 34,
            'required' => false,
            'type' => 'dropdown',
            'source' => 'orphan_needs',
        ],
        'field_creativity_aspects' => [
            'id' => 35,
            'db_column' => 'field_creativity_aspects',
            'display_name' => 'جوانب الإبداع',
            'category' => 'احتياجات وإبداع',
            'category_id' => 7,
            'order' => 35,
            'required' => false,
            'type' => 'dropdown',
            'source' => 'creativity_aspects',
        ],

        // معلومات المعيل
        'field_guardian_health' => [
            'id' => 38,
            'db_column' => 'field_guardian_health',
            'display_name' => 'حالته الصحية',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 10,
            'required' => false,
            'type' => 'dropdown',
            'source' => 'health_statuses',
        ],
        'field_guardian_job' => [
            'id' => 39,
            'db_column' => 'field_guardian_job',
            'display_name' => 'الحالة الوظيفية',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 11,
            'required' => false,
            'type' => 'dropdown',
            'source' => 'employment',
        ],
        'field_guardian_job_text' => [
            'id' => 97,
            'db_column' => 'field_guardian_job_text',
            'display_name' => 'الوظيفة (نص)',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 12,
            'required' => false,
        ],
        'field_dependents_female' => [
            'id' => 40,
            'db_column' => 'field_dependents_female',
            'display_name' => 'عدد من يعيلهم من الإناث',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 13,
            'required' => false,
            'type' => 'number',
        ],
        'field_dependents_male' => [
            'id' => 41,
            'db_column' => 'field_dependents_male',
            'display_name' => 'عدد من يعيلهم من الذكور',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 14,
            'required' => false,
            'type' => 'number',
        ],
        'field_family_members_count' => [
            'id' => 42,
            'db_column' => 'field_family_members_count',
            'display_name' => 'عدد افراد الأسرة مع اليتيم',
            'category' => 'معلومات المعيل',
            'category_id' => 8,
            'order' => 42,
            'required' => false,
        ],

        // معلومات اخوة المكفول
        // تم إزالة حقول "معلومات اخوة المكفول" القديمة
        // سيتم عرض أفراد الأسرة ديناميكياً من جدول re_people

        // تأثير الكفالة والمتابعة
        'field_sponsorship_impact' => [
            'id' => 47,
            'db_column' => 'field_sponsorship_impact',
            'display_name' => 'تأثير الكفالة',
            'category' => 'تأثير الكفالة والمتابعة',
            'category_id' => 10,
            'order' => 47,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['إيجابي جدًا', 'إيجابي', 'متوسط', 'ضعيف'],
        ],
        'field_important_events' => [
            'id' => 48,
            'db_column' => 'field_important_events',
            'display_name' => 'اهم الأحداث التي مرت مع اسرة المكفول',
            'category' => 'تأثير الكفالة والمتابعة',
            'category_id' => 10,
            'order' => 48,
            'required' => false,
        ],
        'field_supervisor_notes' => [
            'id' => 49,
            'db_column' => 'field_supervisor_notes',
            'display_name' => 'ملاحظات المشرف الإجتماعي وتوصياته',
            'category' => 'تأثير الكفالة والمتابعة',
            'category_id' => 10,
            'order' => 49,
            'required' => false,
        ],
        'field_data_update_date' => [
            'id' => 50,
            'db_column' => 'field_data_update_date',
            'display_name' => 'تاريخ تحديث البيانات',
            'category' => 'تأثير الكفالة والمتابعة',
            'category_id' => 10,
            'order' => 50,
            'required' => false,
        ],
        'field_supervisor_name' => [
            'id' => 51,
            'db_column' => 'field_supervisor_name',
            'display_name' => 'إسم المشرف',
            'category' => 'تأثير الكفالة والمتابعة',
            'category_id' => 10,
            'order' => 51,
            'required' => false,
        ],

        // ===== NEW FIELDS - Guardian Data from DATA table =====
        'field_data_id_number' => [
            'id' => 62,
            'db_column' => 'field_data_id_number',
            'display_name' => 'رقم هوية المعيل',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 1,
            'required' => false,
        ],
        'field_data_first_name' => [
            'id' => 63,
            'db_column' => 'field_data_first_name',
            'display_name' => 'الاسم الأول للمعيل',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 2,
            'required' => false,
        ],
        'field_data_father_name' => [
            'id' => 64,
            'db_column' => 'field_data_father_name',
            'display_name' => 'اسم والد المعيل',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 3,
            'required' => false,
        ],
        'field_data_grand_father_name' => [
            'id' => 65,
            'db_column' => 'field_data_grand_father_name',
            'display_name' => 'اسم جد المعيل',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 4,
            'required' => false,
        ],
        'field_data_family_name' => [
            'id' => 66,
            'db_column' => 'field_data_family_name',
            'display_name' => 'اسم العائلة للمعيل',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 5,
            'required' => false,
        ],
        'field_data_birth_date' => [
            'id' => 67,
            'db_column' => 'field_data_birth_date',
            'display_name' => 'تاريخ ميلاد المعيل',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 6,
            'required' => false,
        ],
        'field_data_phone_number' => [
            'id' => 68,
            'db_column' => 'field_data_phone_number',
            'display_name' => 'رقم هاتف المعيل',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 7,
            'required' => false,
        ],
        'field_data_relationship' => [
            'id' => 96,
            'db_column' => 'field_data_relationship',
            'display_name' => 'صلة قرابة المعيل',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 8,
            'required' => false,
        ],
        'field_data_city' => [
            'id' => 71,
            'db_column' => 'field_data_city',
            'display_name' => 'المدينة',
            'category' => 'معلومات السكن',
            'category_id' => 2,
            'order' => 13,
            'required' => false,
        ],
        'field_re_guardian_name' => [
            'id' => 72,
            'db_column' => 'field_re_guardian_name',
            'display_name' => 'اسم الوصي',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 15,
            'required' => false,
        ],
        'field_re_guardian_phone' => [
            'id' => 73,
            'db_column' => 'field_re_guardian_phone',
            'display_name' => 'هاتف الوصي',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 16,
            'required' => false,
        ],
        'field_re_guardian_id' => [
            'id' => 74,
            'db_column' => 'field_re_guardian_id',
            'display_name' => 'رقم هوية الوصي',
            'category' => 'معلومات المعيل التفصيلية',
            'category_id' => 13,
            'order' => 17,
            'required' => false,
        ],

        // ===== NEW FIELDS - Dead People Info =====
        'field_father_id' => [
            'id' => 74,
            'db_column' => 'field_father_id',
            'display_name' => 'رقم هوية الأب',
            'category' => 'معلومات الوالدين المتوفين',
            'category_id' => 14,
            'order' => 74,
            'required' => false,
        ],
        'field_father_first_name' => [
            'id' => 75,
            'db_column' => 'field_father_first_name',
            'display_name' => 'الاسم الأول للأب المتوفى',
            'category' => 'معلومات الوالدين المتوفين',
            'category_id' => 14,
            'order' => 75,
            'required' => false,
        ],
        'field_father_death_date' => [
            'id' => 77,
            'db_column' => 'field_father_death_date',
            'display_name' => 'تاريخ وفاة الأب',
            'category' => 'معلومات الوالدين المتوفين',
            'category_id' => 14,
            'order' => 77,
            'required' => false,
        ],
        'field_father_death_reason' => [
            'id' => 78,
            'db_column' => 'field_father_death_reason',
            'display_name' => 'سبب وفاة الأب',
            'category' => 'معلومات الوالدين المتوفين',
            'category_id' => 14,
            'order' => 78,
            'required' => false,
        ],
        'field_mother_id' => [
            'id' => 78,
            'db_column' => 'field_mother_id',
            'display_name' => 'رقم هوية الأم',
            'category' => 'معلومات الوالدين المتوفين',
            'category_id' => 14,
            'order' => 78,
            'required' => false,
        ],
        'field_mother_first_name' => [
            'id' => 79,
            'db_column' => 'field_mother_first_name',
            'display_name' => 'الاسم الأول للأم',
            'category' => 'معلومات الوالدين المتوفين',
            'category_id' => 14,
            'order' => 79,
            'required' => false,
        ],
        'field_mother_death_date' => [
            'id' => 81,
            'db_column' => 'field_mother_death_date',
            'display_name' => 'تاريخ وفاة الأم',
            'category' => 'معلومات الوالدين المتوفين',
            'category_id' => 14,
            'order' => 81,
            'required' => false,
        ],
        'field_mother_death_reason' => [
            'id' => 82,
            'db_column' => 'field_mother_death_reason',
            'display_name' => 'سبب وفاة الأم',
            'category' => 'معلومات الوالدين المتوفين',
            'category_id' => 14,
            'order' => 82,
            'required' => false,
        ],

        // ===== معلومات الأم (حية أو متوفية) =====
        'field_mother_status' => [
            'id' => 83,
            'db_column' => 'field_mother_status',
            'display_name' => 'هل الأم على قيد الحياة',
            'category' => 'معلومات الأم',
            'category_id' => 13.5,
            'order' => 70,
            'required' => false,
            'type' => 'dropdown',
            'options' => ['حية', 'متوفية'],
        ],
        'field_living_mother_id' => [
            'id' => 88,
            'db_column' => 'field_living_mother_id',
            'display_name' => 'رقم هوية الأم',
            'category' => 'معلومات الأم',
            'category_id' => 13.5,
            'order' => 70.5,
            'required' => false,
        ],
        'field_living_mother_first_name' => [
            'id' => 84,
            'db_column' => 'field_living_mother_first_name',
            'display_name' => 'الاسم الأول للأم',
            'category' => 'معلومات الأم',
            'category_id' => 13.5,
            'order' => 71,
            'required' => false,
        ],
        'field_living_mother_second_name' => [
            'id' => 85,
            'db_column' => 'field_living_mother_second_name',
            'display_name' => 'اسم والد الأم',
            'category' => 'معلومات الأم',
            'category_id' => 13.5,
            'order' => 72,
            'required' => false,
        ],
        'field_living_mother_third_name' => [
            'id' => 86,
            'db_column' => 'field_living_mother_third_name',
            'display_name' => 'اسم جد الأم',
            'category' => 'معلومات الأم',
            'category_id' => 13.5,
            'order' => 73,
            'required' => false,
        ],
        'field_living_mother_last_name' => [
            'id' => 87,
            'db_column' => 'field_living_mother_last_name',
            'display_name' => 'اسم عائلة الأم',
            'category' => 'معلومات الأم',
            'category_id' => 13.5,
            'order' => 73.5,
            'required' => false,
        ],

        // ===== NEW FIELDS - Dead People Info =====
        'field_guardian_id_owner' => [
            'id' => 89,
            'db_column' => 'field_guardian_id_owner',
            'display_name' => 'رقم هوية صاحب الحساب',
            'category' => 'المعلومات البنكية',
            'category_id' => 16,
            'order' => 89,
            'required' => false,
        ],
        'field_guardian_account_owner_name' => [
            'id' => 90,
            'db_column' => 'field_guardian_account_owner_name',
            'display_name' => 'اسم صاحب الحساب',
            'category' => 'المعلومات البنكية',
            'category_id' => 16,
            'order' => 90,
            'required' => false,
        ],
        'field_guardian_bank_name' => [
            'id' => 91,
            'db_column' => 'field_guardian_bank_name',
            'display_name' => 'اسم البنك',
            'category' => 'المعلومات البنكية',
            'category_id' => 16,
            'order' => 91,
            'required' => false,
        ],
        'field_guardian_phone_number' => [
            'id' => 93,
            'db_column' => 'field_guardian_phone_number',
            'display_name' => 'رقم هاتف صاحب الحساب',
            'category' => 'المعلومات البنكية',
            'category_id' => 16,
            'order' => 93,
            'required' => false,
        ],
        'field_guardian_iban_usd' => [
            'id' => 94,
            'db_column' => 'field_guardian_iban_usd',
            'display_name' => 'رقم IBAN بالدولار',
            'category' => 'المعلومات البنكية',
            'category_id' => 16,
            'order' => 94,
            'required' => false,
        ],
        'field_guardian_iban_shekel' => [
            'id' => 95,
            'db_column' => 'field_guardian_iban_shekel',
            'display_name' => 'رقم IBAN بالشيكل',
            'category' => 'المعلومات البنكية',
            'category_id' => 16,
            'order' => 95,
            'required' => false,
        ],
    ],

    // ===== SECTION CONTROL FIELDS - حقول التحكم في الأقسام =====
    'section_fields' => [
        'field_family_members_section' => [
            'id' => 100,
            'db_column' => 'field_family_members_section',
            'display_name' => 'قسم أفراد الأسرة',
            'category' => 'أقسام الصفحة',
            'category_id' => 17,
            'order' => 100,
            'required' => false,
            'is_section' => true,
        ],
        'field_attachments_section' => [
            'id' => 101,
            'db_column' => 'field_attachments_section',
            'display_name' => 'قسم المرفقات والوثائق',
            'category' => 'أقسام الصفحة',
            'category_id' => 17,
            'order' => 101,
            'required' => false,
            'is_section' => true,
        ],
    ],

    'categories' => [
        1 => 'معلومات المكفول الأساسية',
        2 => 'معلومات السكن',
        3 => 'المعلومات الدراسية',
        4 => 'الحالة النفسية والسلوكية',
        5 => 'الجوانب الدينية',
        6 => 'الحالة الصحية',
        7 => 'احتياجات وإبداع',
        8 => 'معلومات المعيل',
        9 => 'معلومات اخوة المكفول',
        10 => 'تأثير الكفالة والمتابعة',
        // 11 => 'معلومات المؤسسة والمرفقات', // تم حذفها - غير مستخدمة
        // 12 => 'معلومات الكفالة', // تم حذفها - غير مستخدمة
        13 => 'معلومات المعيل التفصيلية',
        14 => 'معلومات الوالدين المتوفين',
        15 => 'معلومات الأم',
        16 => 'المعلومات البنكية',
        17 => 'أقسام الصفحة',
    ],
];
