<?php
// auto generated by Laravel IDE Helper
if (!function_exists('generateFiveDigitCode')) {
    /**
     * Generate a unique 6-digit numeric code (e.g., 000001, 000002, etc.)
     *
     * @param string $modelClass Full model class name (e.g., \App\Models\User::class)
     * @param string $column Column name to check uniqueness against (e.g., 'code')
     * @return string
     */
    function generateFiveDigitCode(string $modelClass, string $column = 'code'): string
    {
        $all = $modelClass::pluck($column)->map(function($val) {
            // تأكد من تحويل القيمة إلى رقم صحيح حتى لو كانت نصية مع أصفار بادئة
            return (int)preg_replace('/\D/', '', $val);
        });
        $max = $all->max() ?? 0;
        $next = $max + 1;
        // أرجع الرقم مع الأصفار البادئة
        return str_pad($next, 6, '0', STR_PAD_LEFT);
    }
}

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Log;

if (!function_exists('generateUniqueReservedCode')) {
    /**
     * Generate and reserve a unique 6-digit code based on the max value in a given table/column and reserved_codes.
     * Uses DB transaction and lock to prevent race conditions.
     *
     * @param string $table
     * @param string $column
     * @param string|null $sessionId
     * @return string|null
     */
    function generateUniqueReservedCode(string $table, string $column, ?string $sessionId = null): ?string
    {
        return DB::transaction(function () use ($table, $column, $sessionId) {
            // جلب أكبر رقم رقمي فقط من الجدول الأساسي
            $maxMain = DB::table($table)
                ->select(DB::raw("MAX(CAST($column as UNSIGNED)) as max_code"))
                ->whereRaw("LENGTH($column) = 6 AND $column REGEXP '^[0-9]+$'")
                ->value('max_code');

            // جلب أكبر رقم رقمي فقط من جدول reserved_codes مع قفل للكتابة
            $maxReserved = DB::table('reserved_codes')
                ->select(DB::raw("MAX(CAST(code as UNSIGNED)) as max_code"))
                ->whereRaw("LENGTH(code) = 6 AND code REGEXP '^[0-9]+$'")
                ->lockForUpdate()
                ->value('max_code');

            // احسب الرقم التالي
            $next = max((int)$maxMain, (int)$maxReserved) + 1;
            $code = str_pad($next, 6, '0', STR_PAD_LEFT);

            // تحقق من عدم وجود الرقم في reserved_codes (داخل نفس المعاملة)
            $exists = DB::table('reserved_codes')->where('code', $code)->lockForUpdate()->exists();
            if (!$exists) {
                DB::table('reserved_codes')->insert([
                    'code' => $code,
                    'session_id' => $sessionId ?? Str::uuid(),
                    'reserved_at' => now(),
                    'used' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
                return $code;
            }
            // إذا كان الرقم مستخدم بالفعل (حالة نادرة)، كرر حتى تجد رقم غير مستخدم
            for ($i = 1; $i <= 10; $i++) {
                $next++;
                $code = str_pad($next, 6, '0', STR_PAD_LEFT);
                $exists = DB::table('reserved_codes')->where('code', $code)->lockForUpdate()->exists();
                if (!$exists) {
                    DB::table('reserved_codes')->insert([
                        'code' => $code,
                        'session_id' => $sessionId ?? Str::uuid(),
                        'reserved_at' => now(),
                        'used' => false,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                    return $code;
                }
            }
            // إذا لم يتمكن من توليد رقم فريد
            return null;
        });
    }
}

if (!function_exists('cleanupOldReservedCodes')) {
    /**
     * Delete old, unused reserved codes older than given minutes.
     *
     * @param int $minutes
     * @return int عدد السجلات المحذوفة
     */
    function cleanupOldReservedCodes(int $minutes = 1): int
    {
        return DB::table('reserved_codes')
            ->where('used', false)
            ->where('reserved_at', '<', now()->subMinutes($minutes))
            ->delete();
    }
}

if (!function_exists('generateFileIdFromDataTable')) {
    /**
     * Generate file_id_number using the data table sequence (same algorithm as existing system)
     *
     * @return string
     */
    function generateFileIdFromDataTable(): string
    {
        return DB::transaction(function () {
            // جلب آخر file_id_number من جدول data
            $lastFileId = DB::table('data')
                ->select('file_id_number')
                ->whereNotNull('file_id_number')
                ->whereRaw("file_id_number REGEXP '^[0-9]+$'")
                ->orderByRaw('CAST(file_id_number as UNSIGNED) DESC')
                ->value('file_id_number');

            // حساب الرقم التالي
            $nextNumber = $lastFileId ? ((int)$lastFileId + 1) : 1;

            // إرجاع الرقم مع 6 خانات
            return str_pad($nextNumber, 6, '0', STR_PAD_LEFT);
        });
    }
}

if (!function_exists('getFileIdByIdentityNumber')) {
    /**
     * Get file_id_number for a given identity number from data table
     * If not found, create a new one using the standard algorithm
     *
     * @param string $identityNumber
     * @return string|null
     */
    function getFileIdByIdentityNumber(string $identityNumber): ?string
    {
        // البحث عن رقم الهوية في جدول data
        $record = DB::table('data')
            ->select('file_id_number')
            ->where('person_id', $identityNumber)
            ->orWhere('guardian_id', $identityNumber)
            ->first();

        if ($record && $record->file_id_number) {
            return $record->file_id_number;
        }

        // إذا لم يوجد، إنشاء رقم جديد باستخدام الخوارزمية المعتمدة
        return generateFileIdFromDataTable();
    }
}

if (!function_exists('mapFolderNamesToFileIds')) {
    /**
     * Map folder names (identity numbers) to their corresponding file_id_numbers
     * Used for bulk folder uploads where folder names are identity numbers
     *
     * @param array $identityNumbers Array of identity numbers (folder names)
     * @return array Associative array [identity_number => file_id_number]
     */
    function mapFolderNamesToFileIds(array $identityNumbers): array
    {
        $mapping = [];

        foreach ($identityNumbers as $identityNumber) {
            $fileId = getFileIdByIdentityNumber($identityNumber);
            if ($fileId) {
                $mapping[$identityNumber] = $fileId;
            }
        }

        return $mapping;
    }
}

if (!function_exists('validateIdentityNumber')) {
    /**
     * Validate Saudi Identity Number (10 digits)
     *
     * @param string $identityNumber
     * @return bool
     */
    function validateIdentityNumber(string $identityNumber): bool
    {
        // تنظيف الرقم من أي مسافات أو رموز
        $identityNumber = preg_replace('/\D/', '', $identityNumber);

        // التحقق من أن الرقم بين 8-10 خانات
        $length = strlen($identityNumber);
        if ($length < 8 || $length > 10) {
            return false;
        }

        // للأرقام أقل من 10 خانات، نعتبرها صالحة مباشرة
        if ($length < 10) {
            return true;
        }

        // التحقق من صحة رقم الهوية السعودي (للأرقام 10 خانات)
        $sum = 0;
        for ($i = 0; $i < 9; $i++) {
            if ($i % 2 == 0) {
                $doubled = (int)$identityNumber[$i] * 2;
                $sum += $doubled > 9 ? $doubled - 9 : $doubled;
            } else {
                $sum += (int)$identityNumber[$i];
            }
        }

        $checkDigit = (10 - ($sum % 10)) % 10;
        return $checkDigit == (int)$identityNumber[9];
    }
}

if (!function_exists('sanitizeIdentityNumber')) {
    /**
     * Clean and sanitize identity number
     *
     * @param string $identityNumber
     * @return string|null
     */
    function sanitizeIdentityNumber(string $identityNumber): ?string
    {
        $cleaned = preg_replace('/\D/', '', $identityNumber);

        if (validateIdentityNumber($cleaned)) {
            return $cleaned;
        }

        return null;
    }
}

if (!function_exists('bulkValidateIdentityNumbers')) {
    /**
     * Validate multiple identity numbers and return validation results
     *
     * @param array $identityNumbers
     * @return array
     */
    function bulkValidateIdentityNumbers(array $identityNumbers): array
    {
        $results = [
            'valid' => [],
            'invalid' => [],
            'duplicates' => [],
            'statistics' => [
                'total' => count($identityNumbers),
                'valid_count' => 0,
                'invalid_count' => 0,
                'duplicate_count' => 0
            ]
        ];

        $seen = [];

        foreach ($identityNumbers as $identity) {
            $sanitized = sanitizeIdentityNumber($identity);

            if ($sanitized) {
                if (isset($seen[$sanitized])) {
                    $results['duplicates'][] = $sanitized;
                    $results['statistics']['duplicate_count']++;
                } else {
                    $results['valid'][] = $sanitized;
                    $seen[$sanitized] = true;
                    $results['statistics']['valid_count']++;
                }
            } else {
                $results['invalid'][] = $identity;
                $results['statistics']['invalid_count']++;
            }
        }

        return $results;
    }
}

if (!function_exists('generateUniqueAttachmentRecordNumber')) {
    /**
     * توليد رقم مرفق فريد بالبادئة exc_ للاستخدام في جدول enhanced_attachments
     * يضمن التفرد مع استخدام جدول reserved_codes للحماية من التضارب
     *
     * @param string $sessionId معرف الجلسة الفريد
     * @return string الرقم المولد بصيغة exc_XXXXXX
     */
    function generateUniqueAttachmentRecordNumber(string $sessionId = null): string
    {
        $sessionId = $sessionId ?: 'attachment_' . session()->getId() . '_' . time();

        return DB::transaction(function () use ($sessionId) {
            $maxAttempts = 50;

            for ($attempt = 1; $attempt <= $maxAttempts; $attempt++) {
                // الحصول على أكبر رقم من enhanced_attachments (إزالة البادئة للمقارنة)
                $maxAttachment = DB::table('enhanced_attachments')
                    ->where('record_number', 'LIKE', 'exc_%')
                    ->selectRaw('MAX(CAST(SUBSTRING(record_number, 5) AS UNSIGNED)) as max_num')
                    ->lockForUpdate()
                    ->value('max_num');

                // الحصول على أكبر رقم من reserved_codes للرموز التي تبدأ بـ exc_
                $maxReserved = DB::table('reserved_codes')
                    ->where('code', 'LIKE', 'exc_%')
                    ->selectRaw('MAX(CAST(SUBSTRING(code, 5) AS UNSIGNED)) as max_num')
                    ->lockForUpdate()
                    ->value('max_num');

                // حساب الرقم التالي
                $nextNumber = max((int)$maxAttachment, (int)$maxReserved) + 1;
                $newRecordNumber = 'exc_' . str_pad($nextNumber, 6, '0', STR_PAD_LEFT);

                // التحقق من عدم وجود الرقم في reserved_codes
                $existsInReserved = DB::table('reserved_codes')
                    ->where('code', $newRecordNumber)
                    ->lockForUpdate()
                    ->exists();

                // التحقق من عدم وجود الرقم في enhanced_attachments
                $existsInAttachments = DB::table('enhanced_attachments')
                    ->where('record_number', $newRecordNumber)
                    ->exists();

                if (!$existsInReserved && !$existsInAttachments) {
                    // حجز الرقم في reserved_codes
                    DB::table('reserved_codes')->insert([
                        'code' => $newRecordNumber,
                        'session_id' => $sessionId,
                        'reserved_at' => now(),
                        'used' => false,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);

                    Log::info('Generated unique attachment record number', [
                        'record_number' => $newRecordNumber,
                        'session_id' => $sessionId,
                        'attempt' => $attempt,
                        'max_attachment' => $maxAttachment,
                        'max_reserved' => $maxReserved
                    ]);

                    return $newRecordNumber;
                }
            }

            // إذا فشل في التوليد، استخدم نظام طوارئ
            $emergencyNumber = 'exc_' . substr(time(), -6) . rand(10, 99);
            Log::warning('Using emergency attachment record number', [
                'emergency_number' => $emergencyNumber,
                'session_id' => $sessionId
            ]);

            return $emergencyNumber;
        });
    }
}

