<?php
// auto generated by Laravel IDE Helper
if (!function_exists('generateFiveDigitCode')) {
    /**
     * Generate a unique 6-digit numeric code (e.g., 000001, 000002, etc.)
     *
     * @param string $modelClass Full model class name (e.g., \App\Models\User::class)
     * @param string $column Column name to check uniqueness against (e.g., 'code')
     * @return string
     */
    function generateFiveDigitCode(string $modelClass, string $column = 'code'): string
    {
        $all = $modelClass::pluck($column)->map(function($val) {
            // تأكد من تحويل القيمة إلى رقم صحيح حتى لو كانت نصية مع أصفار بادئة
            return (int)preg_replace('/\D/', '', $val);
        });
        $max = $all->max() ?? 0;
        $next = $max + 1;
        // أرجع الرقم مع الأصفار البادئة
        return str_pad($next, 6, '0', STR_PAD_LEFT);
    }
}

